services:
  nia_namecheap:
    # Use an image built from the Dockerfile in the current directory.
    container_name: nia
    image: idrisniyi94/nia-deployment:nia-20250829015852
    # ports:
    #   - 5099:5000
    env_file:
      - .env
    networks:
      - cloudflared-devops-cont
    volumes:
      - ./uploads:/app/uploads
    restart: always

networks:
  cloudflared-devops-cont:
    external: true
