apiVersion: apps/v1
kind: Deployment
metadata:
  name: nia-deployment
  namespace: nia-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nia-deployment
  template:
    metadata:
      labels:
        app: nia-deployment
    spec:
      containers:
      - name: nia-deployment
        image: idrisniyi94/nia-site:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
