apiVersion: apps/v1
kind: Deployment
metadata:
  name: nia-deployment
  namespace: nia-site
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: nia-deployment
  template:
    metadata:
      labels:
        app: nia-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: custom-label
                    operator: In
                    values:
                      - k8s
      containers:
      - name: nia-deployment
        image: IMAGE_NAME
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 5000
        env:
        - name: ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              name: nia-admin-secret
              key: ADMIN_USERNAME
        - name: ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: nia-admin-secret
              key: ADMIN_PASSWORD
         
        
