apiVersion: apps/v1
kind: Deployment
metadata:
  name: nia-deployment
  namespace: nia-site
spec:
  # replicas: 2
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: custom-label
                operator: In
                values:
                  - k8s
  selector:
    matchLabels:
      app: nia-deployment
  template:
    metadata:
      labels:
        app: nia-deployment
    spec:
      containers:
      - name: nia-deployment
        image: IMAGE_NAME
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
